import type { Metadata } from "next";
import { Atkinson_Hyperlegible, DM_Sans } from "next/font/google";
import "../styles/globals.css";
import "../styles/boilerplate.css";
import Header from "@/components/static/Header";
import Footer from "@/components/static/Footer";
// import purpleBg from "../public/images/ellipse-3.png"
// import greenBg from "../public/images/ellipse-4.png"
// import Image from "next/image";

const atkinson = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--atkinson"
});

const dmSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"],
  variable: "--dmSans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.className} ${dmSans.className} `}
      >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
