import type { Metadata } from "next";
import { Atkinson_Hyperlegible, DM_Sans } from "next/font/google";
import "../styles/globals.css";
import "../styles/boilerplate.css";
import "../styles/fonts.css";

const atkinson = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.className} ${dmSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
