import type { Metadata } from "next";
import { Atkinson_Hyperlegible, DM_Sans } from "next/font/google";
import "../styles/globals.css";
import "../styles/boilerplate.css";
// import purpleBg from "../public/images/ellipse-3.png"
// import greenBg from "../public/images/ellipse-4.png"
// import Image from "next/image";

const atkinson = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--atkinson"
});

const dmSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"],
  variable: "--dmSans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.className} ${dmSans.className} `}
      >
        {/* <Image src={purpleBg} alt="" height={400} width={871} className="absolute right-0" /> */}
        {/* <Image src={greenBg} alt="" height={1044} width={1044} className="fixed z-10 right-0" /> */}
        {children}
      </body>
    </html>
  );
}
